version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mongodb+srv://Oleksandr:WLcxWAmNcDUfoeQ5@cluster0.ko7qb70.mongodb.net/UserEmails?retryWrites=true&w=majority&appName=Cluster0